### PR TITLE
Added einancunlu/Sketch-iOS-Bar-Color-Calculator plugin.

### PR DESCRIPTION
**Pull request by einancunlu**

### CODE REVIEW

**Comment by bomberstudios** [comment]
Great, thanks!

Can you please also modify `plugins.json`? Thanks in advance!

**Comment by einancunlu** [comment]
Oh sorry for miss, updated. Thanks.

**Comment by bomberstudios** [comment]
Yay. Merging!

**Comment by einancunlu** [comment]
Great, thanks! : )

**Pull request merged**
