### PR TITLE
added 'sketch-toggle-layer-visibility' and 'sketch-data-populator'

### PR DESCRIPTION
**Pull request by nitrada**
https://github.com/preciousforever/sketch-toggle-layer-visibility/
https://github.com/preciousforever/sketch-data-populator/

### CODE REVIEW

**Comment by bomberstudios** [comment]
There's a few commas missing in that json file, does `rake` work for you with these changes?

**Comment by nitrada** [comment]
oops sorry, i think i forgot to run the rake file :-/

**Comment by nitrada** [comment]
@bomberstudios oops sorry, i oversaw that obiously! :-/ just corrected the commas and will now try the rake part …

**Comment by bomberstudios** [comment]
Better : )

**Comment by nitrada** [comment]
:)

**Pull request merged**
