### PR TITLE
Document-Focus-Checker-for-Sketch plugin is added.

### PR DESCRIPTION
**Pull request by einancunlu**
https://github.com/einancunlu/Document-Focus-Checker-for-Sketch

### CODE REVIEW

**Comment by bomberstudios** [comment]
Do you really want to merge this? The issue has been fixed in 3.4.3, AFAIK…

**Comment by einancunlu** [comment]
Oh really, I didn't know that. I tried to find beta change logs but couldn't find. Anyway, then I will close the pull request, no need. Thanks.. : )

**Comment by einancunlu** [comment]
I guess 3.4.3 is not the beta. Then I guess I missed the last update because they pulled it off from the App Store.

**Comment by bomberstudios** [comment]
Check http://sketchapp.com/exit for more info on how to continue getting updates : )

**Comment by einancunlu** [comment]
Yeah I saw it but postponed it before without knowing it's an update actually, now applied it, thanks. : )

**Pull request closed without merging**
