### PR TITLE
Add the makerinc/maker-sketch-client-release plugin

### PR DESCRIPTION
**Pull request by jasim**
Hello Team :wave:

The plugin is [here](https://github.com/makerinc/maker-sketch-client-release) if you want to have a look.

Hope you are having a great day :)

### CODE REVIEW

**Comment by christianklotz** [comment]
I tried the plugin, however clicking _Sign-in_ only results in a notification within the Sketch document containing the raw API response. Am I missing something or can you provide information on how to use the plugin?

**Comment by jasim** [comment]
(cc @orthes @bhanusharma)

Hi @christianklotz, sorry about that. We were testing out the release & deploy flow for the plugin using skpm, and it is not ready for production use yet.

I can close this PR now and get back to you once it is ready.

However, for the near future, this plugin is for use by our enterprise customers and will not be available for public use. We wanted to add it to the plugin registry to get auto-updates and easier installation.

We'd be happy to give you a temporary login and walk you through the process once it is live.

Please let me know.

**Comment by mathieudutour** [comment]
You don't have to add it to the registry to get auto-updates! The registry is just the list of plugins showing up on https://www.sketch.com/extensions/plugins/

**Comment by jasim** [comment]
Hi @mathieudutour -- does that mean I can say "no" when `skpm` asks whether it should add the plugin in the registry, and then still use `skpm publish` to auto-update plugins?

Also, would the plugin show up in say Sketch Runner's plugin install list, if this is not listed in the registry? Asking just for confirmation - I think we can send direct links to users to download the plugin, if further updates are automatic.

Thanks!

**Comment by mathieudutour** [comment]
> does that mean I can say "no" when skpm asks whether it should add the plugin in the registry, and then still use skpm publish to auto-update plugins?

yes exactly

> would the plugin show up in say Sketch Runner's plugin install list, if this is not listed in the registry?

Ah probably not, although I'm not entirely sure where the plugin lists comes from

**Comment by jasim** [comment]
Got it. That's been a long-standing confusion for me. I'll close this PR. Thanks!

**Comment by christianklotz** [comment]
@jasim but feel free to let me know when it's ready, best via email developer@sketch.com. Always great to see what plugins get built 🙂

**Pull request closed without merging**
