### PR TITLE
Add info for stark plugin

### PR DESCRIPTION
**Pull request by mfouquet**
This PR adds info for the Stark Plugin.

### CODE REVIEW

**Comment by bomberstudios** [comment]
I'm confused. Are you sure the data you've added is correct?

**Comment by bomberstudios** [comment]
Description mentions nudge distance, web talks about color contrast… 🤔

**Comment by bomberstudios** [comment]
Also, your GitHub username (`owner`) is wrong, I think (should be `mfouquet`)

**Comment by bomberstudios** [comment]
Or rather, `owner` should be `stark-contrast` and `name` should be `stark-sketch-plugin` (if you want Sketch Toolbox to find the plugin)

**Comment by mfouquet** [comment]
Sorry about that - having a heck of a time with this after goofing up my forked repo. Thanks for the help - really appreciate it!

**Comment by bomberstudios** [comment]
No worries. Plugin looks awesome!

**Pull request merged**
