### PR TITLE
Add represent.

### PR DESCRIPTION
**Pull request by lpsBetty**
Please add this plugin to the directory. Thanks!

### CODE REVIEW

**Comment by christianklotz** [comment]
This looks amazing, Danke!

**Comment by christianklotz** [comment]
I'm surprised you'd have to move the plugin to GitHub, the [Runner docs](https://docs.sketchrunner.com/developers) don't mention anything like that. Do you have the other fields set in your `manifest.json`? Also, might be best to ask the Runner team for feedback.

**Comment by lpsBetty** [comment]
@christianklotz we already talked to them. You can run plugin commands via Runner when the plugin is installed, but when you want to install the plugin via Runner then you need a public Github repository (otherwise it is not in their install list).

**Comment by christianklotz** [comment]
Ah, great. Could you have a GitHub repo only containing the `.appcast.xml` and keep hosting the rest wherever you do now?

In any case, once updated just make sure to open a PR with a change updating the appcast URL.

**Pull request merged**
