### PR TITLE
Add the jerry-enebeli/streamline-sketch-plugin plugin

### PR DESCRIPTION
**Pull request by jerry-enebeli**
Hello Team :wave:

The plugin is [here](https://github.com/jerry-enebeli/streamline-sketch-plugin) if you want to have a look.

Hope you are having a great day :)

### CODE REVIEW

**Comment by christianklotz** [comment]
It looks like you plugin repository is not public yet. Can you double check and confirm once it's available? Thank you!

**Comment by christianklotz** [comment]
@jerry-enebeli just checking if you are still planning to make this plugin availably publicly. In case you prefer it to remain a private repo, we can close this pull request. Please let me know, thank you!

**Comment by christianklotz** [comment]
Closing for now. Happy to reopen as soon as plugin becomes publicly available.

**Comment by jerry-enebeli** [comment]
hello christianklotz, sorry for the late reply. so i spoke to my cto and he want to have a conversation with you concerning the plugin. are you open for a conversation?

**Comment by christianklotz** [comment]
Sure, feel free to ask questions here or in the forum on sketchplugins.com. For anything reach out to developer@sketch.com

**Pull request closed without merging**
