### PR TITLE
Add the AMoreaux/Sketch-Icons plugin

### PR DESCRIPTION
**Pull request by AMoreaux**

### CODE REVIEW

**Comment by bomberstudios** [comment]
Didn't I just literally merge this? :D

**Comment by AMoreaux** [comment]
I switch with skpm to publish just now. sorry.

**Comment by bomberstudios** [comment]
Ok, I'll merge this and clean up the JSON a bit (I can't have two entries for the same plugin! : )

Also, I'm opening a couple of issues in the skpm repo to improve the PRs that are created automatically when publishing.

**Comment by AMoreaux** [comment]
OK thanks 👍

**Pull request closed without merging**
