### PR TITLE
Update VisualEyes plugin info

### PR DESCRIPTION
**Pull request by dimitrisraptis96**
Update the following information about my plugin: 
- name
- author and
- description

### CODE REVIEW

**Comment by christianklotz** [comment]
Can you make the changes directly in `plugin.json`? The `README` gets generated from it and we use the JSON file as source for https://sketch.com/extensions, too.

**Comment by dimitrisraptis96** [comment]
> Can you make the changes directly in `plugin.json`? The `README` gets generated from it and we use the JSON file as source for https://sketch.com/extensions, too.

Sure! I just create a PR in plugin.json, right?

**Comment by christianklotz** [comment]
Just add another commit with the changes. I’ll recreate the `README` anyway

**Comment by dimitrisraptis96** [comment]
Done! Thank for your help

**Pull request closed without merging**
