### PR TITLE
Add Sketch Proportional Replicator

### PR DESCRIPTION
**Pull request by AleLudovici**
https://github.com/AleLudovici/sketch-proportional-replicator

### CODE REVIEW

**Comment by bomberstudios** [comment]
Will add this manually in a minute, closing the pull request (sorry! : )

**Comment by AleLudovici** [comment]
Hi! @bomberstudios I can't see my plugin added. Should I open an issue or a PR?

**Comment by bomberstudios** [comment]
It's definitely there: see https://www.dropbox.com/s/81pye614hbr102m/Screenshot%202016-03-02%2012.25.02.png?dl=0 and https://www.dropbox.com/s/cjshsqikpvgfmss/Screenshot%202016-03-02%2012.25.43.png?dl=0

**Comment by AleLudovici** [comment]
Yes! Thanks ;)

**Pull request closed without merging**
