### PR TITLE
Add the rnmp/sensive-sketch plugin

### PR DESCRIPTION
**Pull request by rnmp**
Hello Ale :wave:

The plugin is [here](https://github.com/rnmp/sensive-sketch) if you want to have a look.

Hope you are having a great day :)

### CODE REVIEW

**Comment by mathieudutour** [comment]
I see a bunch of call to `localhost:5000` in your code. Are you sure it is ready to be published?

**Comment by mathieudutour** [comment]
Got it, you can use the `—no-registry` option to skip the release here

**Comment by rnmp** [comment]
@mathieudutour Thank you! Kinda related question: is there a resource you can point me about using environment variables at build time? That way it can be `localhost:5000` while developing but `sensive.co` while deploying/publishing here.

**Comment by mathieudutour** [comment]
you can create a `webpack.skpm.config.js` file at the root of your project and mutate the webpack config to add an env plugin

**Pull request closed without merging**
