### PR TITLE
Add Sketch-Contrast

### PR DESCRIPTION
**Pull request by romannurik**

### CODE REVIEW

**Comment by romannurik** [comment]
Dup

**Comment by bt7893** [comment]
Your plug-in is extremely promising and will save me so much time. However, some values does not look accurate when sampled. Values of the same text / background color are giving me mixed results.

screen shot 2018-10-04 at 2 03 09 pm
screen shot 2018-10-04 at 2 02 59 pm

**Comment by romannurik** [comment]
Hi there! If you could send me your Sketch file I can take a look. Also it'll be easier if you file this in the original repository for the plugin (romannurik/Sketch-Contrast)

**Comment by bt7893** [comment]
Hi Roman, Thank you for your prompt response. I have submitted this on the original repository. Thank you once again for your help!
-Bobby

**Pull request closed without merging**
