### PR TITLE
Added mludowise/sketch-create-nested-symbol

### PR DESCRIPTION
**Pull request by mludowise**
Added plugin to create nested symbols.

### CODE REVIEW

**Comment by einancunlu** [comment]
Hi, are you sure nesting symbols by using current symbol API purely doesn't cause problems? I mean if it was that simple, why Sketch team didn't allow it in first place I wonder. : )

**Comment by mludowise** [comment]
My script is basically a shortcut to the steps outlined in this article:
https://www.designernews.co/stories/24265-psa-you-can-use-nested-symbols-in-sketch <https://www.designernews.co/stories/24265-psa-you-can-use-nested-symbols-in-sketch>

In fairness, Sketch responded to the article and said, "If your document turns itself into a burning ball of fire, don't be surprised if the answer from our support team is: 'we told you not to do that’”.

I have been using this workaround pretty frequently and haven’t run into any issues, but that doesn’t mean that it won’t happen.

If you’re not comfortable adding it to the plugin-directory, I completely understand. I’m also amenable to adding a disclaimer in the README.

-Mel

**Comment by einancunlu** [comment]
Oh I'm not the admin of plugin-directory, just someone with curiosity. : ) Hmm interesting... Anyway I hope things go well and we would be able to use nested symbols in this way or another way!

**Comment by mludowise** [comment]
@einancunlu lol. You did bring up a good point though, so I added a disclaimer to the README.

**Pull request merged**
