### PR TITLE
Remove Protoship Codegen from plugins registry

### PR DESCRIPTION
**Pull request by jasim**
I'm the author of this plugin and I would like to remove it from the plugins registry. Thanks.

### CODE REVIEW

**Comment by christianklotz** [comment]
Can you make the changes in `plugins.json` directly? The `README.md` will be updated automatically. Thank you!

**Comment by christianklotz** [comment]
@jasim let me know if you want to make the change in `plugins.json` within this PR or open a new one. Thank you

**Comment by jasim** [comment]
@christianklotz I've raised a new PR for this, thanks. https://github.com/sketchplugins/plugin-directory/pull/1060

Once the plugin is removed from plugins.json, would auto-updates stop? I'm removing this because I'd like users to install it through the website and not discover it through plugin runners. I'd still like to have Sketch's plugin auto-update working.

**Comment by christianklotz** [comment]
The auto update is based on the appcast which must be specified in `plugins.json`. Runner uses the JSON as one source as far as I know. Don’t know if there are ways to exclude your plugin from Runner, you’d have to check with them.

What’s the reason for not including it in Runner if I may ask? Are there alternatives to get more people to visit your website without decreasing the visibility of your plugin?

**Comment by jasim** [comment]
@christianklotz The reason to remove it from plugins.json is to limit casual users from getting frustrated because the design-to-code conversion process is quite involved. They have to spend some time learning to use the tool to be productive. https://protoship.io/docs/learn/

If it is freely available in Runner when users search for "design to code", then they'll come in with the wrong expectation and get frustrated at the learning curve.

**Comment by christianklotz** [comment]
Okay, thank you for the clarification. Closing this issue since the entry got removed in the JSON file in #1060, `README` will be updated automatically.

**Pull request closed without merging**
