### PR TITLE
Continuous integration

### PR DESCRIPTION
**Pull request by pravdomil**
**Changes**
- sources are now stored in two files
  - [`directory/git.txt`](https://github.com/pravdomil/plugin-directory/blob/ci/directory/github.txt) for any git hosted plugins
  - [`directory/external.json`](https://github.com/pravdomil/plugin-directory/blob/ci/directory/external.json) for the rest
- output file is the same [`plugins.json`](https://github.com/pravdomil/plugin-directory/blob/ci/directory/plugins.json)
  - now is's autogenerated file and should not be modified
  - there is no breaking changes
  - now json is checked against [schema](https://github.com/pravdomil/plugin-directory/blob/ci/index.d.ts) and [I must fill some missing fields](https://github.com/sketchplugins/plugin-directory/commit/f2c55d09e0744e78a887c8bd123fd11a24ad6032)

**Features**
- for git plugins
  - following fields `title desc author homepage appcast` is auto updated from plugin `manifest.json` so there is no need for updates from author side
  - also `lastUpdated ` field is taken from git last commit date

**CI process**
- so that CI can update repo environmental variable [`GH_TOKEN `](https://github.com/settings/tokens/new) is needed
- `plugins.json` is generated only in main repo not for PRs because of CI cache (cloning all 443 repos for each PR is not efficient)
- for more info check [ci script](https://github.com/pravdomil/plugin-directory/blob/ci/bin/ci)

I hope that I mention everything, let me know if you have any questions.

[Repo preview](https://github.com/pravdomil/plugin-directory/tree/ci).

*Please do not merge anything else since it will be difficult to rebase my branch.*

### CODE REVIEW

**Comment by pravdomil** [comment]
@bomberstudios for every you commit I need to rebase my branch, do you think that you can take a look at this PR?

**Comment by mathieudutour** [comment]
just so you know, we are going to move away from this repo soon so I don't think we are going to refactor everything now but I'll let @bomberstudios decide

**Comment by pravdomil** [comment]
@bomberstudios hi, can you take a look at this PR? I added support for gitlab now.

**Comment by pravdomil** [comment]
@mathieudutour @bomberstudios can you please take a look at it before merging into master?

**Comment by christianklotz** [comment]
I'm closing this PR because we're already working on the registry, see my [post on Sketch Plugins](https://sketchplugins.com/d/1295-a-quick-sketch-api-update). Until then the current setup is going to serve us well.

**Pull request closed without merging**
