### PR TITLE
request to add Symbol Browser

### PR DESCRIPTION
**Pull request by pratikjshah**
reated pull request to add a new Sketch plugin called "Symbol Browser"

### CODE REVIEW

**Comment by pratikjshah** [comment]
Hi, @christianklotz just checking in! I see that my pull request has been merged but I am not able to see my plugin name in the readme file.

**Comment by christianklotz** [comment]
The `README` gets regenerated every so often, it's now included 🙂

**Comment by pratikjshah** [comment]
Thank you

**Comment by christianklotz** [comment]
The top lost is sorted alphabetically in the `README` and it's additionally listed on the Sketch website where you can search for it https://www.sketch.com/extensions/plugins/.

**Comment by pratikjshah** [comment]
Hey.. I was asking about the sketch website.. where the list used to show recently added first. But I can see that my plugin is at the very bottom. Is there a sorting logic there?

**Comment by christianklotz** [comment]
All entries in `plugins.json` are expected to be in the order they were added, with the first item being the oldest. The website uses the reverse order. It looks like you added yours at the top, therefor accidentally making it "the oldest".

To fix it, please open a PR and move before [`sketch-plugin-brandfolder`](https://github.com/sketchplugins/plugin-directory/blob/master/plugins.json#L5672-L5673) to retain the order of the originally filed PRs.

**Comment by pratikjshah** [comment]
Oh! I didn't know that!
I have raised a new pull request #930 with the correct order.

**Pull request merged**
