### PR TITLE
Corrected Typo in the Repo name

### PR DESCRIPTION
**Pull request by designedbyDC**

### CODE REVIEW

**Comment by bomberstudios** [comment]
Could you also update the README file, please? Thanks in advance!

**Comment by designedbyDC** [comment]
The README file has been updated.

**Comment by bomberstudios** [comment]
Sorry, I meant the plugins.json!

**Comment by designedbyDC** [comment]
done. sorry :)

**Comment by bomberstudios** [comment]
Perfect! : )

**Pull request merged**
