### PR TITLE
Add the elankiderman/qz-plugin plugin

### PR DESCRIPTION
**Pull request by elankiderman**
Hello Ale :wave:

The plugin is [here](https://github.com/elankiderman/qz-plugin) if you want to have a look.

Hope you are having a great day :)

### CODE REVIEW

**Comment by elankiderman** [comment]
@christianklotz i'm new to sketch plugin development and a bit of a github novice. is there a reason this wasn't merged today together with the other pull requests?

**Comment by christianklotz** [comment]
@elankiderman you were quicker than me 🙂 Was in the middle of writing this comment.

I just wanted to ask if you're ok with having your internal plugin showing up publicly on our Sketch Plugin Directory but also through the other installers, Sketchpacks and Sketch Runner? If that's ok with you I'm happy to merge.

**Comment by elankiderman** [comment]
@christianklotz yea i'm fine with that, i figured this would be the easiest way to circulate updates to my team. but it's possible there's a better way that i'm unaware of.

**Comment by christianklotz** [comment]
Ok, in which case you'd have to re-open the pull-request though 🙂

**Comment by christianklotz** [comment]
Ah, ignore my comment. Just saw the other one

**Pull request closed without merging**
