### PR TITLE
Added Beatflyer Lite

### PR DESCRIPTION
**Pull request by nuthinking**
New plugin. It's the lite version of the standalone app [Beatflyer](https://beatflyer.com/). Works similarly to the [popular version](https://www.figma.com/community/plugin/776923340646658146/BeatFlyer-Lite) available for Figma.

### CODE REVIEW

**Comment by bomberstudios** [comment]
Took it for a spin and couldn’t get it to work. I get an error dialog like this:

Screenshot 2021-11-05 at 19 00 27

Any idea what I’m doing wrong?

**Comment by nuthinking** [comment]
Hi @bomberstudios, thanks for looking into it! Is there a way I can test the bundle locally? I simply used `npm run build` to package it. And I tested it locally with `npm run watch`.

**Comment by nuthinking** [comment]
Ah, I guess your artboard is empty?

**Comment by nuthinking** [comment]
Published version 1.1. Still not sure why in Sketch it doesn't pick up the new icon 🤔

Screenshot 2021-11-05 at 19 30 34

Also now shows a new version is available locally but it doesn't let me update 🤷‍♂️

**Comment by nuthinking** [comment]
Removed the old symlink and exported the 1.1 again. Now it should be kind of fine. Still no icon.

**Comment by nuthinking** [comment]
Fixed also the icon 🚀

Screenshot 2021-11-05 at 19 44 38

**Pull request merged**
