### PR TITLE
Added paxos-raft

### PR DESCRIPTION
**Pull request by prateekrastogi**
Hi,

Since skpm only work on darwin and not on linux, I had to open this pull request. Please merge and do let me know of any issues.
My appcast file is at: https://raw.githubusercontent.com/paxos-raft/paxos-raft/master/lib/sketch/appcast.xml

### CODE REVIEW

**Comment by christianklotz** [comment]
🤔 I just tried the appcast and noticed the archive [`0.0.28.zip`](https://github.com/paxos-raft/paxos-raft/archive/v0.0.28.zip) is the entire repo, not the Sketch plugin.

```
<enclosure url="https://github.com/paxos-raft/paxos-raft/archive/v0.0.28.zip" sparkle:version="0.0.28"/>
```

After manually installing the plugin from the subfolder it's located in and running it I get a _🙌 It's alive_ notification within the document window but that's it. It might be best to review the project setup and follow the instructions in step [*2. Submit manually*](https://developer.sketch.com/plugins/publish-a-plugin) and ensure the release includes the latest build artefact of the Sketch plugin.

Once done, add the entry directly into `plugins.json` and it should be good to go.

**Comment by prateekrastogi** [comment]
@christianklotz Thank you for reverting back. It's still a work in progress and it was just an alpha release. I will make sure release includes latest build artefact of sketch plugin. I guess by `plugins.json` you mean package.json, or is it a new file that I have to make?

Also, can you link me with documentation of `.sketch tar .json files markup fields`?  As most of sketch competitors are already parsing .sketch file and locking it up with custom binary serialization. Reverse engineering entire .sketch document can introduce bugs in my plugin.

**Comment by christianklotz** [comment]
By `plugins.json` I mean adding your plugin, once done, to this registry.

See this [example](https://github.com/sketchplugins/plugin-directory/blob/master/plugins.json#L6513-L6521):

```json
  {
    "title": "Potrace",
    "description": "Convert bitmaps to vector graphics",
    "name": "sketch-potrace",
    "owner": "perrysmotors",
    "appcast": "https://raw.githubusercontent.com/perrysmotors/sketch-potrace/master/.appcast.xml",
    "homepage": "https://github.com/perrysmotors/sketch-potrace",
    "author": "Giles Perry"
  }
```

For the Sketch File Format we provide full documentation and links to the official JSON Schema and TypeScript types at https://developer.sketch.com/file-format/

**Comment by prateekrastogi** [comment]
@christianklotz Thank you again for providing clarifying details and specs. I will make sure everything aligns as how you mentioned.

**Comment by prateekrastogi** [comment]
Just updated the my plugin in the format you desired. Also, new location of my appcast file is:
https://raw.githubusercontent.com/paxos-raft/paxos-raft/master/.appcast.xml

Please merge my pull request.

**Comment by christianklotz** [comment]
Almost there, the `.zip` currently is `lib/sketch/paxos-raft.sketchplugin`. Make sure the archive contains the `.sketchplugin` without any nested folders and it's ready to go.

**Comment by prateekrastogi** [comment]
Just pushed those changes. Now, it should be ready to go.

**Pull request merged**
