### PR TITLE
Updated RemoveAllGuides with appcast

### PR DESCRIPTION
**Pull request by ichik**

### CODE REVIEW

**Comment by bomberstudios** [comment]
Could you please check the PR? There are changes in README.md that shouldn't be there if you've only changed the appcast for your plugin

**Comment by ichik** [comment]
Oh, wow. That's weird. Was a result of running `rake` somehow.

**Comment by ichik** [comment]
So, apparently README.md and plugins.json are out of sync. There are multiple outdated descriptions and a few missing plugins present in json, but missing from README.

**Comment by ichik** [comment]
Unfortunately I've dropped the fork and redid the commit again before investigating the original repo, so I made a new pull request.

**Pull request closed without merging**
